Test E2E:
  WP:
    - '7.1'
  allow-failure:
    - false

Test PHPUnit:
  WP:
    - '7.1'
  PHP:
    - '8.4'
    - '8.3'
    - '8.2'
    - '8.1'
    - '8.0'
    - '7.4'
  LLMS:
    - ''
  allow-failure:
    - false
  name-append:
    - ''
