Test E2E:
  WP:
    - 'latest'
    - '6.2'
    - '6.1'
    - '6.0'
    - '5.9'
  allow-failure:
    - false

  include:
    - WP: 'nightly'
      allow-failure: true

Test PHPUnit:
  WP:
    - '6.3'
    - '6.2'
    - '6.1'
    - '6.0'
    - '5.9'
  PHP:
    - '8.1'
    - '8.0'
    - '7.4'
  LLMS:
    - ''
  allow-failure:
    - false
  name-append:
    - ''

  include:
    - PHP: '8.1'
      WP: 'nightly'
      allow-failure: true
    - name-append: ' (LLMS nightly)'
