name: Sync Organization Files

on:
  push:
    paths:
      # E2E Test File.
      - .github/workflow-templates/test-e2e.yml

      # ES Lint File.
      - .github/workflow-templates/lint-js.yml

      # JS Unit Test File.
      - .github/workflow-templates/test-js-unit.yml

      # PHP Files.
      - .github/workflow-templates/coding-standards.yml
      - .github/workflow-templates/php-test-coverage.yml
      - .github/workflow-templates/test-phpunit.yml

      # Utils.
      - .github/workflows/keep-alive.yml
      - .github/workflows/project-automation.yml
      - .github/workflow-templates/sync-branches.yml

      # When this file is edited.
      - .github/workflows/workflow-sync.yml
    branches:
      - trunk
  workflow_dispatch:

env:
  DRY_RUN: false

  CLI_FILES: |
    .github/workflow-templates/coding-standards.yml=.github/workflows/coding-standards.yml
    .github/workflow-templates/test-phpunit.yml=.github/workflows/test-phpunit.yml

  E2E_TEST_REPOS: |
    gocodebox/lifterlms
    gocodebox/lifterlms-advanced-videos
    gocodebox/lifterlms-blocks
    gocodebox/lifterlms-groups

  ES_LINT_REPOS: |
    gocodebox/lifterlms
    gocodebox/lifterlms-blocks
    gocodebox/lifterlms-advanced-videos
    gocodebox/lifterlms-custom-fields
    gocodebox/lifterlms-gateway-paypal
    gocodebox/lifterlms-stripe

  JS_UNIT_REPOS: |
    gocodebox/lifterlms
    gocodebox/lifterlms-gateway-paypal

  PHP_FILES: |
    .github/workflow-templates/coding-standards.yml=.github/workflows/coding-standards.yml
    .github/workflow-templates/php-test-coverage.yml=.github/workflows/php-test-coverage.yml
    .github/workflow-templates/test-phpunit.yml=.github/workflows/test-phpunit.yml
  PHP_REPOS: |
    gocodebox/lifterlms
    gocodebox/lifterlms-advanced-quizzes
    gocodebox/lifterlms-advanced-videos
    gocodebox/lifterlms-assignments
    gocodebox/lifterlms-blocks
    gocodebox/lifterlms-convertkit
    gocodebox/lifterlms-custom-fields
    gocodebox/lifterlms-gateway-authorize-net
    gocodebox/lifterlms-gateway-paypal
    gocodebox/lifterlms-groups
    gocodebox/lifterlms-helper
    gocodebox/lifterlms-integration-gravity-forms
    gocodebox/lifterlms-integration-ninja-forms
    gocodebox/lifterlms-integration-twilio
    gocodebox/lifterlms-integration-woocommerce
    gocodebox/lifterlms-integration-wpforms
    gocodebox/lifterlms-mailchimp
    gocodebox/lifterlms-pdfs
    gocodebox/lifterlms-private-areas
    gocodebox/lifterlms-rest
    gocodebox/lifterlms-social-learning
    gocodebox/lifterlms-stripe
    gocodebox/lifterlms-com-paypal-connect
    gocodebox/lifterlms-private-site
    gocodebox/lifterlms-course-cohorts

  # Utility workflows.
  UTIL_FILES: |
    .github/workflows/keep-alive.yml
    .github/workflows/project-automation.yml
    .github/workflow-templates/.editorconfig=.editorconfig
    .github/workflow-templates/sync-branches.yml=.github/workflows/sync-branches.yml
  UTIL_REPOS: |
    gocodebox/lifterlms
    gocodebox/lifterlms-advanced-quizzes
    gocodebox/lifterlms-advanced-videos
    gocodebox/lifterlms-assignments
    gocodebox/lifterlms-blocks
    gocodebox/lifterlms-convertkit
    gocodebox/lifterlms-cli
    gocodebox/lifterlms-custom-fields
    gocodebox/lifterlms-gateway-authorize-net
    gocodebox/lifterlms-gateway-paypal
    gocodebox/lifterlms-groups
    gocodebox/lifterlms-helper
    gocodebox/lifterlms-integration-formidable-forms
    gocodebox/lifterlms-integration-gravity-forms
    gocodebox/lifterlms-integration-ninja-forms
    gocodebox/lifterlms-integration-twilio
    gocodebox/lifterlms-integration-woocommerce
    gocodebox/lifterlms-integration-wpforms
    gocodebox/lifterlms-labs
    gocodebox/lifterlms-lite-lms-progress-tracker
    gocodebox/lifterlms-mailchimp
    gocodebox/lifterlms-pdfs
    gocodebox/lifterlms-private-areas
    gocodebox/lifterlms-rest
    gocodebox/lifterlms-social-learning
    gocodebox/lifterlms-stripe
    gocodebox/lifterlms-virtual-classrooms
    gocodebox/lifterlms-launchpad
    gocodebox/lifterlms-launchpad-child
    gocodebox/sky-pilot
    gocodebox/lifterlms-zapier
    gocodebox/llms-api-node
    gocodebox/private-issues
    gocodebox/snippets
    gocodebox/dev-tools
    gocodebox/lifterlms-brand
    gocodebox/lifterlms-lib-tasks
    gocodebox/lifterlms-cs
    gocodebox/lifterlms-tests
    gocodebox/llms-releaser
    gocodebox/lifterlms.com
    gocodebox/myliftersite.com
    gocodebox/developer.lifterlms.com
    gocodebox/telemetry.lifterlms.com
    gocodebox/llms-academy-rest
    gocodebox/lifterlms-com-reporting
    gocodebox/lifterlms-com-experiments
    gocodebox/lifterlms.com-rest-api
    gocodebox/lifterlms-com-support-desk
    gocodebox/lifterlms-private-site
    gocodebox/lifterlms-course-cohorts

jobs:

  cli-files:
    name: LLMS-CLI Test Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sync workflow files
        uses: varunsridharan/action-github-workflow-sync@main
        with:
          DRY_RUN: ${{ env.DRY_RUN }}
          REPOSITORIES: |
            gocodebox/lifterlms-cli
          WORKFLOW_FILES: ${{ env.CLI_FILES }}
          GITHUB_TOKEN: ${{ secrets.ORG_WORKFLOWS }}
          COMMIT_MESSAGE: "PHPCS & PHP Testing Workflow File Sync [Runner ID: $GITHUB_RUN_NUMBER]"

  e2e-test:
    name: E2E Test File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sync workflow files
        uses: varunsridharan/action-github-workflow-sync@main
        with:
          DRY_RUN: ${{ env.DRY_RUN }}
          REPOSITORIES: ${{ env.E2E_TEST_REPOS }}
          WORKFLOW_FILES: |
            .github/workflow-templates/test-e2e.yml=.github/workflows/test-e2e.yml
          GITHUB_TOKEN: ${{ secrets.ORG_WORKFLOWS }}
          COMMIT_MESSAGE: "E2E Test Workflow File Sync [Runner ID: $GITHUB_RUN_NUMBER]"

  eslint:
    name: Lint JS File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sync workflow files
        uses: varunsridharan/action-github-workflow-sync@main
        with:
          DRY_RUN: ${{ env.DRY_RUN }}
          REPOSITORIES: ${{ env.ES_LINT_REPOS }}
          WORKFLOW_FILES: |
            .github/workflow-templates/lint-js.yml=.github/workflows/lint-js.yml
          GITHUB_TOKEN: ${{ secrets.ORG_WORKFLOWS }}
          COMMIT_MESSAGE: "Lint JS Workflow File Sync [Runner ID: $GITHUB_RUN_NUMBER]"

  js-unit:
    name: JS Unit File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sync workflow files
        uses: varunsridharan/action-github-workflow-sync@main
        with:
          DRY_RUN: ${{ env.DRY_RUN }}
          REPOSITORIES: ${{ env.JS_UNIT_REPOS }}
          WORKFLOW_FILES: |
            .github/workflow-templates/test-js-unit.yml=.github/workflows/test-js-unit.yml
          GITHUB_TOKEN: ${{ secrets.ORG_WORKFLOWS }}
          COMMIT_MESSAGE: "Test JS Unit Workflow File Sync [Runner ID: $GITHUB_RUN_NUMBER]"

  php-workflows:
    name: PHP Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sync workflow files
        uses: varunsridharan/action-github-workflow-sync@main
        with:
          DRY_RUN: ${{ env.DRY_RUN }}
          REPOSITORIES: ${{ env.PHP_REPOS }}
          WORKFLOW_FILES: ${{ env.PHP_FILES }}
          GITHUB_TOKEN: ${{ secrets.ORG_WORKFLOWS }}
          COMMIT_MESSAGE: "PHP Workflow File Sync [Runner ID: $GITHUB_RUN_NUMBER]"

  util-files:
    name: Utility Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sync workflow files
        uses: varunsridharan/action-github-workflow-sync@main
        with:
          DRY_RUN: ${{ env.DRY_RUN }}
          REPOSITORIES: ${{ env.UTIL_REPOS }}
          WORKFLOW_FILES: ${{ env.UTIL_FILES }}
          GITHUB_TOKEN: ${{ secrets.ORG_WORKFLOWS }}
          COMMIT_MESSAGE: "Utility File Sync [Runner ID: $GITHUB_RUN_NUMBER]"
